#!/usr/bin/env bash
# A bash script thats configures a new Ubuntu machine 
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
