#!/usr/bin/env bash
# Bash cthat onfigures a new Ubuntu machine to respect above requirements

# STEP 1 - make updates
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# It must return a page that contains the string Hello World!
echo "Hello World!" > /var/www/html/index.html

# Nginx server block is modified to include a redirect
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.judyjanice.com permanent;"
sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
service nginx restart

