#!/usr/bin/env bash
# Script to set up HAProxy on lb-01 server, sendin' traffic to web-01 and web-02
# Requests will use the roundrobin algorithm for distribution
# Ensure HAProxy is managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

# Addin' the server config to HAProxy config file
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
