#!/usr/bin/env bash
# Script to set up HAProxy on lb-01 server, sendin' traffic to web-01 and web-02
# Requests will use the roundrobin algorithm for distribution
# Ensure HAProxy is managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure to use roundrubin algorithm
echo '
frontend judyjanice.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 122516-web-01 35.168.8.63:80
        server 122516-web-02 100.26.50.151:80
' >> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

