#!/usr/bin/env bash
# It will display 'To infinity and beyond' indefinitely, and 'I am invincible!!!' when getting SIGTERM.

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done